// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       uuid.UUID
	Username pgtype.Text
	Name     pgtype.Text
	Password pgtype.Text
}
