// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const changeTaskName = `-- name: ChangeTaskName :exec
UPDATE tasks SET name = $2 WHERE id = $1
`

type ChangeTaskNameParams struct {
	ID   uuid.UUID
	Name pgtype.Text
}

func (q *Queries) ChangeTaskName(ctx context.Context, arg ChangeTaskNameParams) error {
	_, err := q.db.Exec(ctx, changeTaskName, arg.ID, arg.Name)
	return err
}

const changeTaskStatus = `-- name: ChangeTaskStatus :exec
UPDATE tasks SET status = $2 WHERE id = $1
`

type ChangeTaskStatusParams struct {
	ID     uuid.UUID
	Status pgtype.Bool
}

func (q *Queries) ChangeTaskStatus(ctx context.Context, arg ChangeTaskStatusParams) error {
	_, err := q.db.Exec(ctx, changeTaskStatus, arg.ID, arg.Status)
	return err
}

const changeTaskText = `-- name: ChangeTaskText :exec
UPDATE tasks SET task = $2 WHERE id = $1
`

type ChangeTaskTextParams struct {
	ID   uuid.UUID
	Task pgtype.Text
}

func (q *Queries) ChangeTaskText(ctx context.Context, arg ChangeTaskTextParams) error {
	_, err := q.db.Exec(ctx, changeTaskText, arg.ID, arg.Task)
	return err
}

const createTask = `-- name: CreateTask :many
INSERT INTO tasks (id, userid, name, task, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, status
`

type CreateTaskParams struct {
	ID     uuid.UUID
	Userid pgtype.UUID
	Name   pgtype.Text
	Task   pgtype.Text
	Status pgtype.Bool
}

type CreateTaskRow struct {
	ID     uuid.UUID
	Name   pgtype.Text
	Status pgtype.Bool
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) ([]CreateTaskRow, error) {
	rows, err := q.db.Query(ctx, createTask,
		arg.ID,
		arg.Userid,
		arg.Name,
		arg.Task,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateTaskRow
	for rows.Next() {
		var i CreateTaskRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getAllTasksFromUser = `-- name: GetAllTasksFromUser :many
SELECT id, userid, name, task, status FROM tasks WHERE userid = $1
`

func (q *Queries) GetAllTasksFromUser(ctx context.Context, userid pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAllTasksFromUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Name,
			&i.Task,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :many
SELECT name, task, status FROM tasks WHERE id = $1
`

type GetTaskByIDRow struct {
	Name   pgtype.Text
	Task   pgtype.Text
	Status pgtype.Bool
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) ([]GetTaskByIDRow, error) {
	rows, err := q.db.Query(ctx, getTaskByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskByIDRow
	for rows.Next() {
		var i GetTaskByIDRow
		if err := rows.Scan(&i.Name, &i.Task, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskStatusByID = `-- name: GetTaskStatusByID :many
SELECT name, status FROM tasks WHERE id = $1
`

type GetTaskStatusByIDRow struct {
	Name   pgtype.Text
	Status pgtype.Bool
}

func (q *Queries) GetTaskStatusByID(ctx context.Context, id uuid.UUID) ([]GetTaskStatusByIDRow, error) {
	rows, err := q.db.Query(ctx, getTaskStatusByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskStatusByIDRow
	for rows.Next() {
		var i GetTaskStatusByIDRow
		if err := rows.Scan(&i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
