// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, name, password
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateUserParams struct {
	Username pgtype.Text
	Name     pgtype.Text
	Password pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Name, arg.Password)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
